### ISSUE TITLE
preparing the data issue

### ISSUE THREAD

**Issue by Khalleud** [jermp/rdf_indexes#1]
i've got an issue in " python extract_vocabs.py ../test_data/wordnet31.gz -S -P -O" command, it says
"if string[pos] == '<':
IndexError: index out of range" 
in line 114, in parse_nq of rdf_parser.py
and i can't really find how to overpass it

**Comment by jermp** [comment]
Hi,
you are probably using python3 and not python 2.7.
If you use python 2.7 it should work fine.
Thanks anyway for reporting this, I will look into what to do with python3.
The problem is in the 'gzip' module.
In python2, gzip returns a line as a string, whereas python3 returns it as a *binary* string.

**Comment by jermp** [comment]
I have updated the scripts to work with python3.

**Comment by Khalleud** [comment]
thanks for responding quickly
